# Allow anonymous connections
allow_anonymous true

# Verbose logging to debug bridge connections
log_type error
log_type warning
log_type notice
log_type information

# Listener for local clients (relay subscribes here)
listener 1884
protocol mqtt

# Bridge to HiveMQ Cloud - receive only
connection hivemq-cloud
address 694a1aae27d0437e9e34b72c7be0568f.s1.eu.hivemq.cloud:8883
bridge_protocol_version mqttv311
try_private false
remote_username test_wot
remote_password test_wot
topic application/d209ff97-929d-46f8-9180-ea2f6c382e90/device/# in 0
bridge_attempt_unsubscribe false
notifications false
cleansession true
bridge_cafile /mosquitto/config/isrgrootx1.pem
bridge_tls_version tlsv1.2
start_type automatic
restart_timeout 5